# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/bd/bluex_v_2_1/ip/bluex_v_2_1_alu_ex_0_0/bluex_v_2_1_alu_ex_0_0.xci
# IP: The module: 'bluex_v_2_1_alu_ex_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: D:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/bd/bluex_v_2_1/ip/bluex_v_2_1_alu_ex_0_0/bluex_v_2_1_alu_ex_0_0.xci
# IP: The module: 'bluex_v_2_1_alu_ex_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet
