# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/bd/bluex_v_2_1/ip/bluex_v_2_1_matcop_0_0/bluex_v_2_1_matcop_0_0.xci
# IP: The module: 'bluex_v_2_1_matcop_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: d:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.gen/sources_1/bd/bluex_v_2_1/ip/bluex_v_2_1_matcop_0_0/bluex_v_2_1_matcop_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bluex_v_2_1_matcop_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/bd/bluex_v_2_1/ip/bluex_v_2_1_matcop_0_0/bluex_v_2_1_matcop_0_0.xci
# IP: The module: 'bluex_v_2_1_matcop_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: d:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.gen/sources_1/bd/bluex_v_2_1/ip/bluex_v_2_1_matcop_0_0/bluex_v_2_1_matcop_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bluex_v_2_1_matcop_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
